name: whatsapp_clone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_picker: ^2.0.20
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  flutter_contacts: ^1.1.7
  uuid: ^3.0.7
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  giphy_get: ^2.0.4
  emoji_picker_flutter: ^1.6.1
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  agora_uikit: ^1.3.3
  audio_waveforms: ^1.0.4
  cached_video_player: ^2.0.4
  video_player: ^2.6.0
  audioplayers: ^4.1.0
  swipe_to: ^1.0.2
  sms_autofill: ^2.3.0
  image_cropper: ^4.0.1
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"
  color_dark: "#121212"

  image: assets/images/wa_logo.png


  cupertino_icons: ^1.0.2
