// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWQDmWoSRdmVOn67nWVSP3Ir7vkaAOoM',
    appId: '1:245616005261:web:ac28e89919affed1ef52c4',
    messagingSenderId: '245616005261',
    projectId: 'whatsapp-clone-65035',
    authDomain: 'whatsapp-clone-65035.firebaseapp.com',
    storageBucket: 'whatsapp-clone-65035.appspot.com',
    measurementId: 'G-Q9ZH1BZ1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GrVqrgwapLSkP8iFBzORzft9ENpouWo',
    appId: '1:245616005261:android:d446b8ef033779a0ef52c4',
    messagingSenderId: '245616005261',
    projectId: 'whatsapp-clone-65035',
    storageBucket: 'whatsapp-clone-65035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5MD52jLfErjx7mCeC0DRAR43Ul9Z_hCQ',
    appId: '1:245616005261:ios:53e80e7f7dee1f1cef52c4',
    messagingSenderId: '245616005261',
    projectId: 'whatsapp-clone-65035',
    storageBucket: 'whatsapp-clone-65035.appspot.com',
    iosClientId: '245616005261-gc4ppurc8v7lsu8p1i0n4pnh116lc89l.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
